version: "3.8"
services:
  todo-app:
    build: .
    image: todo-app:latest
    container_name: todo-app
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 80
